# vim ft=yaml
# Build some standard python wheels for the travis worker
language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
install:
    - WHEELHOUSE=$PWD/wheelhouse
    - pip wheel -w $WHEELHOUSE cython
    # matplotlib dependencies
    - sudo apt-get install libpng-dev libfreetype6-dev
    - pip install wheel
    - pip wheel -w $WHEELHOUSE matplotlib
    # scipy dependencies
    - sudo apt-get install libblas-dev liblapack-dev libatlas3gf-base gfortran
    # scipy needs -v flag otherwise travis times out for lack of output
    - pip wheel -w $WHEELHOUSE -v scipy
    # Pillow
    - sudo apt-get install libtiff4-dev libwebp-dev
    - pip wheel -w $WHEELHOUSE -v pillow
script:
    - pip install -f $WHEELHOUSE cython scipy matplotlib pillow
before_deploy: cd $WHEELHOUSE
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
      secure: "ilWZL8wbTP/DNDMQgIsD2UfFOwofhEVqjiejyfM+/J9HcbKpzB08G5a1HIlT/mN1bmbVwXZLhhGGUg7U2XHdpBgCW3JEN8bRVj4MnIaG6Uu+cobPyV85YBmhN7tZPHhDoW2BHqi6wP96PdSCCVGD6S86/IGhSnUDLL7IG3VdgIw="
  region: ORD
  container: wheels
  skip_cleanup: true
