# vim ft=yaml
# Build some standard python wheels for the travis worker
language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
install:
    - if [ "${TRAVIS_PYTHON_VERSION:0:1}" == 2 ]; then
        NUMPY_VERSION=1.6.0;
      else
        NUMPY_VERSION=1.7.1;
      fi
    - WHEELHOUSE=$PWD/wheelhouse
    - pip install wheel
    - pip wheel -w $WHEELHOUSE cython
    - pip wheel -w $WHEELHOUSE https://github.com/cython/cython/archive/0.19.2.tar.gz
    # Install Cython for builds
    - pip install -f $WHEELHOUSE cython
    # numpy, scipy dependencies
    - sudo apt-get install libblas-dev liblapack-dev libatlas3gf-base gfortran
    # Build required numpy version
    - pip wheel -w $WHEELHOUSE numpy==$NUMPY_VERSION
    # Install numpy for building other wheels against
    - pip install -f $WHEELHOUSE numpy==$NUMPY_VERSION
    # matplotlib dependencies
    - sudo apt-get install libpng-dev libfreetype6-dev
    - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then
        pip wheel -w $WHEELHOUSE matplotlib==1.3.1;
      else
        pip wheel -w $WHEELHOUSE matplotlib;
      fi
    # scipy needs -v flag otherwise travis times out for lack of output
    - pip wheel -w $WHEELHOUSE -v scipy
    # Pillow
    - sudo apt-get install libtiff4-dev libwebp-dev
    - pip wheel -w $WHEELHOUSE -v pillow
    # Networkx
    - pip wheel -w $WHEELHOUSE -v networkx
    # Tifffile
    - pip wheel -w $WHEELHOUSE -v tifffile
script:
    - pip install -f $WHEELHOUSE cython numpy==$NUMPY_VERSION scipy matplotlib pillow networkx tifffile
before_deploy: cd $WHEELHOUSE
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
      secure: "ilWZL8wbTP/DNDMQgIsD2UfFOwofhEVqjiejyfM+/J9HcbKpzB08G5a1HIlT/mN1bmbVwXZLhhGGUg7U2XHdpBgCW3JEN8bRVj4MnIaG6Uu+cobPyV85YBmhN7tZPHhDoW2BHqi6wP96PdSCCVGD6S86/IGhSnUDLL7IG3VdgIw="
  region: ORD
  container: travis_wheels
  skip_cleanup: true
