# vim ft=yaml
# Build some standard python wheels for the travis worker
language: python
env:
    global:
       # Choose the package names you want to build here
       - TO_BUILD="cython numpy scipy matplotlib pillow networkx tifffile h5py cvxopt"
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
install:
    - WHEELHOUSE=$PWD/wheelhouse
    - if [ "${TRAVIS_PYTHON_VERSION:0:1}" == 2 ]; then
        NUMPY_VERSION=1.6.0;
      else
        NUMPY_VERSION=1.7.1;
      fi
    - source travis_install.sh
script:
    - pip install --no-index -f $WHEELHOUSE $TO_BUILD
before_deploy: cd $WHEELHOUSE
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
      secure: "ilWZL8wbTP/DNDMQgIsD2UfFOwofhEVqjiejyfM+/J9HcbKpzB08G5a1HIlT/mN1bmbVwXZLhhGGUg7U2XHdpBgCW3JEN8bRVj4MnIaG6Uu+cobPyV85YBmhN7tZPHhDoW2BHqi6wP96PdSCCVGD6S86/IGhSnUDLL7IG3VdgIw="
  region: ORD
  container: travis_wheels
  skip_cleanup: true
