# vim ft=yaml
# Build some standard python wheels for the travis worker
language: python
env:
    global:
       # List packages you want to build here, maybe with versions
       # e.g numpy scipy matplotlib==1.3.1 ipython
       - TO_BUILD=pandas
       # Any Python packages that need installing before you build the wheels
       - PRE_BUILD=""
       # Override default numpy version for packages needing numpy
       #- NUMPY_VERSION==1.5.1
python:
    - 2.6
    - 2.7
    #- 3.2
    - 3.3
    - 3.4
install:
    - export WHEELHOUSE=$PWD/wheelhouse
    # Set base numpy version for packages requiring numpy
    # Allow override by setting global variable NUMPY_VERSION
    - |
      if [ -z $NUMPY_VERSION ]; then
        if [ "${TRAVIS_PYTHON_VERSION:0:1}" == 2 ]; then
            export NUMPY_VERSION=1.6.0
        else
            export NUMPY_VERSION=1.7.1
        fi
      fi;
    - pip install -U pip
    - python travis_install.py
script:
    - pip install --no-index -f $WHEELHOUSE $TO_BUILD
before_deploy: cd $WHEELHOUSE
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
      secure: "ilWZL8wbTP/DNDMQgIsD2UfFOwofhEVqjiejyfM+/J9HcbKpzB08G5a1HIlT/mN1bmbVwXZLhhGGUg7U2XHdpBgCW3JEN8bRVj4MnIaG6Uu+cobPyV85YBmhN7tZPHhDoW2BHqi6wP96PdSCCVGD6S86/IGhSnUDLL7IG3VdgIw="
  region: ORD
  container: travis_wheels
  skip_cleanup: true
