# vim ft=yaml
# Build some standard python wheels for the travis worker
language: python
env:
    global:
       # Choose the package names you want to build here
       #- TO_BUILD="cython numpy scipy matplotlib pillow networkx tifffile h5py cvxopt"
       - TO_BUILD="cvxopt"
python:
    - 2.7
install:
    - WHEELHOUSE=$PWD/wheelhouse
    - pip wheel -w $WHEELHOUSE https://github.com/cython/cython/archive/0.18.zip
    - PIPW="pip wheel -w $WHEELHOUSE"
    - sudo apt-get install libblas-dev liblapack-dev libatlas3gf-base gfortran
    - pip install -f $WHEELHOUSE cython==0.18
    - $PIPW numpy==1.5.1
    - pip install -f $WHEELHOUSE numpy==1.5.1
    - $PIPW -v scipy==0.9.0
    - $PIPW nibabel
script:
    - pip install --no-index -f $WHEELHOUSE scipy nibabel
before_deploy: cd $WHEELHOUSE
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
      secure: "ilWZL8wbTP/DNDMQgIsD2UfFOwofhEVqjiejyfM+/J9HcbKpzB08G5a1HIlT/mN1bmbVwXZLhhGGUg7U2XHdpBgCW3JEN8bRVj4MnIaG6Uu+cobPyV85YBmhN7tZPHhDoW2BHqi6wP96PdSCCVGD6S86/IGhSnUDLL7IG3VdgIw="
  region: ORD
  container: travis_wheels
  skip_cleanup: true
