# vim ft=yaml
# Build some standard python wheels for the travis worker
language: python
python:
    - 2.6
    - 2.7
install:
    - WHEELHOUSE=$PWD/wheelhouse
    - pip wheel -w $WHEELHOUSE pydicom==0.9.7
    - pip wheel -w $WHEELHOUSE pydicom==0.9.8
script:
    - pip install --no-index -f $WHEELHOUSE pydicom
before_deploy: cd $WHEELHOUSE
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
      secure: "ilWZL8wbTP/DNDMQgIsD2UfFOwofhEVqjiejyfM+/J9HcbKpzB08G5a1HIlT/mN1bmbVwXZLhhGGUg7U2XHdpBgCW3JEN8bRVj4MnIaG6Uu+cobPyV85YBmhN7tZPHhDoW2BHqi6wP96PdSCCVGD6S86/IGhSnUDLL7IG3VdgIw="
  region: ORD
  container: travis_wheels
  skip_cleanup: true
